### ISSUE TITLE
Permission `limit` field use cases?

### ISSUE THREAD

**Issue by sherryyuan-gcp** [HL7/data-access-policies#15]
On the spec, it mentioned we support [limit](https://build.fhir.org/permission-definitions.html#Permission.rule.limit) that define what limits apply to the use of data, by security labels. I wonder what is the use case for this particular field, can we achieve the same thing by using combination of actor, purpose, action field?

If we have to require configurations on prohibit disclosure without information, would it make more sense to have a store level configuration instead of a per-permission?

**Comment by sherry-s-yuan** [comment]
Bringing this discussion to zulip chat: https://chat.fhir.org/#narrow/stream/179247-Security-and-Privacy/topic/Permission.20.60limit.60.20field/near/397813674
