### ISSUE TITLE
Permission Data Field Cardinality and AND/OR

### ISSUE THREAD

**Issue by sherryyuan-gcp** [HL7/data-access-policies#24]
## Background

Currently in [FHIR Consent](https://hl7.org/fhir/R5/consent.html)

1. [Provisions](https://hl7.org/fhir/R5/consent-definitions.html#Consent.provision) at the same level of depth are interpreted as disjunctive (i.e., OR-ed). This means that matching any of the sibling provisions at one level constitutes an exception to the rule stated in the parent provision.
2. Within a provision, the conditions implied by different attributes are interpreted conjunctively (i.e., AND-ed). This means that in order to match the provision, all the attributes must match. (e.g. if code, expression and data period are defined, they all must match)
3. Within an attribute, if the attribute is multi-valued, the values are interpreted as disjunctive (i.e., OR-ed). This means that matching any of the values listed for the attribute is sufficient for the attribute to match. For single-valued attributes, matching is simply based on matching the value of the attribute.

### FHIR Consent Limitations

We cannot represent AND condition for multiple [security label](https://hl7.org/fhir/R5/consent-definitions.html#Consent.provision.securityLabel). e.g. the data must match both [label1, label2]

## FHIR Permission and its potential fix

In [FHIR Permission](https://build.fhir.org/permission.html), [data](https://build.fhir.org/permission-definitions.html#Permission.rule.data) is a repeated field, we can make data repeat field OR-ed together, and each inner field repetition AND-ed.

For example (proposed change is in the comments `//`):
```
    "data" : [{ // OR-ed together
      "resource" : { // Should not be repeated
        "meaning" : "<code>",
        "reference" : { Reference(Any) }
      },
      "security" : [{ Coding }], // AND-ed together
      "period" : { Period },  // Should not be repeated
      "expression" : { Expression }
    }],
```

Similarly for activity
```
    "activity" : [{ // OR-ed together
      "actor" : [{ Reference }], // AND-ed together
      "action" : [{ CodeableConcept }], // AND-ed together
      "purpose" : [{ CodeableConcept }] // AND-ed together
    }],
```

This way user can represent their data attribute matching criteria with [disjunctive normal form](https://en.wikipedia.org/wiki/Disjunctive_normal_form). Therefore, solves the AND problem that Consent resource is having.

**Comment by JohnMoehrke** [comment]
Note one fundamental difference Permission has from Consent is that at the .rule level there is the .combining rule logic. Thus what the rule is at the .rule level is not purely an "OR" which is the case in Consent.

**Comment by JohnMoehrke** [comment]
Your proposal is that at the .data and .activity level repetitions are OR-ed . Yet the releationship between .type, .data, activity and .limit are AND-ed. That is for a rule.type of 'permit' to be a permit, the data must match some defined pattern, the activity must match some defined pattern, and the limit will be applied. Thus I think repetitions within .data and within .actictivity would seem better to define as AND-ed. Thus only leaf elements within .data and within .activity are OR-ed.

Given that recognition of the meaning of elements within .rule, I think I propose the opposite of your proposal.

We can still get AND logic. For example to get a permit rule that will work only against data that has a security tag of A plus B plus C. We have one rule of permit, with three repetitions of .data; thus .data[0].security=A, .data[1].security=B, and .data[2].security=C. 

if we want A or B or C. then we have just one .data with the repetitions at the .security level.

**Comment by JohnMoehrke** [comment]
Conclusion: 
1. Clarify that at the data and activity repetitions -- OR relationship (e.g. multiple .activity mean that any of them are selected)
2. Clarify that at the elements within data and activity repetitions -- AND (e.g. multiple .security mean that the data must have all values on the data .meta.security)
3. Downgrade .period to 0..1 as the only AND relationship between multiple periods can be expressed as one period

**Comment by JohnMoehrke** [comment]
https://jira.hl7.org/browse/FHIR-43583
https://jira.hl7.org/browse/FHIR-44748

**Comment by sherryyuan-gcp** [comment]
To add on, the data.resource should also become 0..1 cardinality

**Comment by JohnMoehrke** [comment]
> To add on, the data.resource should also become 0..1 cardinality

So you are saying that any AND logic between two(or more) data resources are not useful? I think that would be true if we only had a .meaning of instance, related, or dependent. but because we have a .meaning of authored then there is a chance of a useful use-case (data authored by Bob related to this CarePlan). 
We could agree to move the authored use out to a .data.authored level; which would then allow us to have a limited set of types of resources.  (I would prefer this).

**Comment by sherryyuan-gcp** [comment]
Right, I cannot imagine a case where users want to match data attribute `CarePlan/id1` and `CarePlan/id2`, these two have no overlaps, and AND-ing them together yield no result.

**Comment by JohnMoehrke** [comment]
so then do you agree we should move the author concept out?

**Comment by JohnMoehrke** [comment]
![image](https://github.com/HL7/data-access-policies/assets/29581687/78e49962-61cd-4c9b-b1da-1d75d33f57ce)

**Comment by JohnMoehrke** [comment]
that from the Event pattern

**Comment by sherryyuan-gcp** [comment]
Moved discussion to https://chat.fhir.org/#narrow/stream/179247-Security-and-Privacy/topic/Permission.2FConsent.20attribute.20AND.2FOR/near/421685745

**Comment by JohnMoehrke** [comment]
@sherryyuan-gcp is this issue now resolved with the updates to the Permission resource? If not, what is not yet resolved. If there is more to resolve, should those be identified as their own issue so that this broader one can be closed?
